"""Image helpers for Dreame lawn mower entities."""

from __future__ import annotations

from io import BytesIO

from PIL import Image, ImageDraw


def png_bytes_to_jpeg(image_bytes: bytes) -> bytes:
    """Convert rendered PNG bytes to JPEG for Home Assistant snapshots."""
    with Image.open(BytesIO(image_bytes)) as image:
        converted = image.convert("RGB")
        output = BytesIO()
        converted.save(output, format="JPEG", quality=90)
        return output.getvalue()


def map_placeholder_jpeg(
    *,
    title: str = "Dreame map unavailable",
    detail: str | None = None,
    width: int = 1024,
    height: int = 768,
) -> bytes:
    """Return a valid JPEG placeholder for failed map refreshes."""
    image = Image.new("RGB", (width, height), (28, 32, 36))
    draw = ImageDraw.Draw(image)
    accent = (80, 170, 220)
    text = (235, 238, 242)
    muted = (165, 172, 180)

    draw.rounded_rectangle(
        (96, 96, width - 96, height - 96),
        radius=32,
        outline=accent,
        width=4,
    )
    draw.text((140, 150), title, fill=text)
    draw.text(
        (140, 205),
        detail or "No map image was returned by the mower.",
        fill=muted,
    )
    draw.text(
        (140, height - 170),
        "This placeholder is generated by the Home Assistant integration.",
        fill=muted,
    )

    output = BytesIO()
    image.save(output, format="JPEG", quality=90)
    return output.getvalue()
