"""Bundled reusable Dreame lawn mower client implementation."""

from .client import (
    DreameLawnMowerAuthError,
    DreameLawnMowerClient,
    DreameLawnMowerConnectionError,
    DreameLawnMowerError,
    DreameLawnMowerTwoFactorRequiredError,
)
from .app_protocol import (
    MOWER_ERROR_PROPERTY_KEY,
    MOWER_PROPERTY_HINTS,
    MOWER_RAW_STATUS_PROPERTY_KEY,
    MOWER_STATE_LABELS,
    MOWER_STATE_PROPERTY_KEY,
    decode_mower_status_blob,
    mower_error_label,
    mower_state_label,
)
from .apk_research import (
    DEFAULT_APK_RESEARCH_TERMS,
    DEFAULT_DECOMPILED_SOURCE_SUFFIXES,
    analyze_decompiled_sources,
    analyze_dreamehome_apk,
    build_jadx_command,
    find_jadx_executable,
    run_jadx_decompile,
)
from .camera_probe import CAMERA_PROBE_PROPERTY_KEYS, build_camera_probe_payload
from .map_probe import (
    MAP_PROBE_PROPERTY_KEYS,
    build_cloud_property_summary,
    build_map_probe_payload,
)
from .models import (
    DISPLAY_NAME_ALIASES,
    MODEL_NAME_MAP,
    SUPPORTED_ACCOUNT_TYPES,
    DreameLawnMowerCameraFeatureSupport,
    DreameLawnMowerDescriptor,
    DreameLawnMowerFirmwareUpdateSupport,
    DreameLawnMowerMapDiagnostics,
    DreameLawnMowerMapSummary,
    DreameLawnMowerMapView,
    DreameLawnMowerRemoteControlSupport,
    DreameLawnMowerSnapshot,
    DreameLawnMowerStatusBlob,
    display_name_for_model,
    firmware_update_support_from_device,
    map_diagnostics_from_device,
    map_summary_from_map_data,
    map_summary_to_dict,
)

__all__ = [
    "DreameLawnMowerAuthError",
    "DreameLawnMowerCameraFeatureSupport",
    "DreameLawnMowerClient",
    "DreameLawnMowerConnectionError",
    "DreameLawnMowerDescriptor",
    "DreameLawnMowerError",
    "DreameLawnMowerFirmwareUpdateSupport",
    "DreameLawnMowerMapDiagnostics",
    "DreameLawnMowerMapSummary",
    "DreameLawnMowerMapView",
    "DreameLawnMowerRemoteControlSupport",
    "DreameLawnMowerSnapshot",
    "DreameLawnMowerStatusBlob",
    "DreameLawnMowerTwoFactorRequiredError",
    "DEFAULT_APK_RESEARCH_TERMS",
    "DEFAULT_DECOMPILED_SOURCE_SUFFIXES",
    "DISPLAY_NAME_ALIASES",
    "MODEL_NAME_MAP",
    "CAMERA_PROBE_PROPERTY_KEYS",
    "MAP_PROBE_PROPERTY_KEYS",
    "MOWER_ERROR_PROPERTY_KEY",
    "MOWER_PROPERTY_HINTS",
    "MOWER_RAW_STATUS_PROPERTY_KEY",
    "MOWER_STATE_LABELS",
    "MOWER_STATE_PROPERTY_KEY",
    "SUPPORTED_ACCOUNT_TYPES",
    "analyze_decompiled_sources",
    "analyze_dreamehome_apk",
    "build_jadx_command",
    "build_camera_probe_payload",
    "build_cloud_property_summary",
    "build_map_probe_payload",
    "decode_mower_status_blob",
    "find_jadx_executable",
    "display_name_for_model",
    "firmware_update_support_from_device",
    "map_diagnostics_from_device",
    "map_summary_from_map_data",
    "map_summary_to_dict",
    "mower_error_label",
    "mower_state_label",
    "run_jadx_decompile",
]
