"""Point-cloud generation limits and supported firmware contracts."""

# Dreame and MOVA can report 3D-map PCD payloads with a "*.bin" object name.
_POINT_CLOUD_OBJECT_EXTENSIONS = frozenset({"pcd", "bin"})
_POINT_CLOUD_ACKNOWLEDGED_FIXED_OBJECT_MODELS = frozenset({"mova.mower.g2583"})
_POINT_CLOUD_ANNOUNCEMENT_PROPERTY_KEY = "99.20"
_POINT_CLOUD_ANNOUNCEMENT_CLOCK_SKEW_MS = 5_000
_POINT_CLOUD_ANNOUNCEMENT_PROBE_TIMEOUT_SECONDS = 2.0
_POINT_CLOUD_ANNOUNCEMENT_INITIAL_BUDGET_FRACTION = 0.05
_POINT_CLOUD_ANNOUNCEMENT_REPROBE_TIMEOUT_SECONDS = 0.5
_POINT_CLOUD_ANNOUNCEMENT_REPROBE_ATTEMPTS = 3
_POINT_CLOUD_ANNOUNCEMENT_RETRY_MAX_SECONDS = 8.0
_POINT_CLOUD_CLOUD_SETUP_TIMEOUT_SECONDS = 20.0
_POINT_CLOUD_LEGACY_POLL_TIMEOUT_SECONDS = 2.0
_POINT_CLOUD_LEGACY_BASELINE_TIMEOUT_SECONDS = 20.0
_POINT_CLOUD_STORED_DOWNLOAD_TIMEOUT_SECONDS = 5.0
# Forced generation can read a dedicated announcement or a legacy OBJ baseline,
# then download a fixed-key baseline identity before dispatching o:10.
_POINT_CLOUD_GENERATION_PREFLIGHT_BUDGET_SECONDS = (
    _POINT_CLOUD_ANNOUNCEMENT_PROBE_TIMEOUT_SECONDS
    + _POINT_CLOUD_LEGACY_BASELINE_TIMEOUT_SECONDS
    + _POINT_CLOUD_STORED_DOWNLOAD_TIMEOUT_SECONDS
)
# A stored request can additionally try a cached object and a stored legacy
# baseline before downloading that baseline again for fixed-key identity.
# This legacy path is longer than the dedicated-announcement path.
_POINT_CLOUD_STORED_PREFLIGHT_BUDGET_SECONDS = (
    _POINT_CLOUD_ANNOUNCEMENT_PROBE_TIMEOUT_SECONDS
    + _POINT_CLOUD_LEGACY_BASELINE_TIMEOUT_SECONDS
    + (3 * _POINT_CLOUD_STORED_DOWNLOAD_TIMEOUT_SECONDS)
)
